In [2]:
# -*- coding: utf-8 -*-   
      
import os  

def file_name(file_dir):   
    for root, dirs, files in os.walk(file_dir):  
        print(root) #当前目录路径  
        print(dirs) #当前路径下所有子目录  
        print(files) #当前路径下所有非目录子文件

In [6]:
# -*- coding: utf-8 -*-   
      
import os  

def file_name(file_dir):   
    L=[]   
    for root, dirs, files in os.walk(file_dir):  
        for file in files:  
            if os.path.splitext(file)[1] == '.jpeg':  
                L.append(os.path.join(root, file))  
    return L  


#其中os.path.splitext()函数将路径拆分为文件名+扩展名

In [8]:
# -*- coding: utf-8 -*-  
import os  

def listdir(path, list_name):  #传入存储的list
    for file in os.listdir(path):  
        file_path = os.path.join(path, file)  
        if os.path.isdir(file_path):  
            listdir(file_path, list_name)  
        else:  
            list_name.append(file_path)

In [9]:
file_name(r"C:\\Users\\dell\\Documents\\WeChat Files\\fy_Luffy\\Files\\upDate\\minutes\\A.DCE\\")

[]

In [10]:
filenames = []
listdir(r"C:\\Users\\dell\\Documents\\WeChat Files\\fy_Luffy\\Files\\upDate\\minutes\\A.DCE\\",filenames)

In [12]:
filenames[0]

'C:\\\\Users\\\\dell\\\\Documents\\\\WeChat Files\\\\fy_Luffy\\\\Files\\\\upDate\\\\minutes\\\\A.DCE\\\\A1803.DCE.csv'

In [13]:
import pandas as pd 
import numpy as np

In [16]:
a = pd.read_csv(filenames[0])

In [17]:
a

              Unnamed: 0    open    high     low   close  volume
0    2018-03-02 09:14:00  3231.0  3231.0  3231.0  3231.0     0.0
1    2018-03-02 09:16:00  3231.0  3231.0  3231.0  3231.0     2.0
2    2018-03-02 09:17:00  3231.0  3231.0  3231.0  3231.0     2.0
3    2018-03-02 09:26:00  3231.0  3231.0  3231.0  3231.0     0.0
4    2018-03-02 09:27:00  3248.0  3248.0  3248.0  3248.0     4.0
5    2018-03-02 09:28:00  3248.0  3248.0  3248.0  3248.0     0.0
6    2018-03-02 10:37:00  3248.0  3248.0  3248.0  3248.0     0.0
7    2018-03-02 10:38:00  3248.0  3248.0  3248.0  3248.0     0.0
8    2018-03-02 10:45:00  3248.0  3248.0  3248.0  3248.0     0.0
9    2018-03-02 10:55:00  3248.0  3248.0  3248.0  3248.0     0.0
10   2018-03-02 11:00:00  3248.0  3248.0  3248.0  3248.0     0.0
11   2018-03-02 11:12:00  3231.0  3231.0  3231.0  3231.0     2.0
12   2018-03-02 11:13:00  3280.0  3280.0  3280.0  3280.0     2.0
13   2018-03-02 11:18:00  3280.0  3280.0  3280.0  3280.0     0.0
14   2018-03-02 11:24:00  3280.0  3280.0  3280.0  3280.0     0.0
15   2018-03-02 11:26:00  3280.0  3280.0  3280.0  3280.0     0.0
16   2018-03-02 13:32:00  3280.0  3280.0  3280.0  3280.0     0.0
17   2018-03-02 13:38:00  3280.0  3280.0  3280.0  3280.0     0.0
18   2018-03-02 14:31:00  3280.0  3280.0  3280.0  3280.0     0.0
19   2018-03-02 14:32:00  3252.0  3252.0  3252.0  3252.0    18.0
20   2018-03-02 14:35:00  3250.0  3250.0  3250.0  3250.0     4.0
21   2018-03-02 14:36:00  3250.0  3250.0  3240.0  3240.0    40.0
22   2018-03-02 14:41:00  3240.0  3240.0  3240.0  3240.0     0.0
23   2018-03-02 15:00:00  3240.0  3240.0  3240.0  3240.0     0.0
24   2018-03-02 21:11:00  3270.0  3270.0  3270.0  3270.0     2.0
25   2018-03-02 21:12:00  3270.0  3270.0  3270.0  3270.0    20.0
26   2018-03-02 21:13:00  3270.0  3270.0  3270.0  3270.0     0.0
27   2018-03-02 21:14:00  3270.0  3270.0  3270.0  3270.0     0.0
28   2018-03-02 21:16:00  3270.0  3270.0  3270.0  3270.0     2.0
29   2018-03-02 21:17:00  3270.0  3270.0  3270.0  3270.0    18.0
..                   ...     ...     ...     ...     ...     ...
90   2018-03-05 13:35:00  3262.0  3262.0  3262.0  3262.0     0.0
91   2018-03-05 13:37:00  3262.0  3262.0  3262.0  3262.0     0.0
92   2018-03-05 13:41:00  3262.0  3262.0  3262.0  3262.0     0.0
93   2018-03-05 13:44:00  3262.0  3272.0  3262.0  3272.0    46.0
94   2018-03-05 14:17:00  3272.0  3272.0  3272.0  3272.0     0.0
95   2018-03-05 14:28:00  3272.0  3272.0  3272.0  3272.0     0.0
96   2018-03-05 14:59:00  3268.0  3268.0  3268.0  3268.0    10.0
97   2018-03-05 15:00:00  3268.0  3268.0  3268.0  3268.0     0.0
98   2018-03-06 13:38:00  3265.0  3265.0  3264.0  3264.0    12.0
99   2018-03-06 13:41:00  3264.0  3264.0  3264.0  3264.0     0.0
100  2018-03-06 13:43:00  3264.0  3264.0  3264.0  3264.0     0.0
101  2018-03-06 13:44:00  3264.0  3264.0  3264.0  3264.0     0.0
102  2018-03-06 13:46:00  3264.0  3264.0  3264.0  3264.0     0.0
103  2018-03-06 14:09:00  3271.0  3271.0  3270.0  3270.0    38.0
104  2018-03-06 14:13:00  3270.0  3270.0  3270.0  3270.0     0.0
105  2018-03-06 14:14:00  3270.0  3270.0  3270.0  3270.0    20.0
106  2018-03-06 14:15:00  3271.0  3271.0  3271.0  3271.0    22.0
107  2018-03-06 14:24:00  3270.0  3270.0  3270.0  3270.0    18.0
108  2018-03-06 14:26:00  3270.0  3270.0  3270.0  3270.0    22.0
109  2018-03-06 14:28:00  3270.0  3270.0  3270.0  3270.0    40.0
110  2018-03-06 14:29:00  3270.0  3270.0  3270.0  3270.0     0.0
111  2018-03-06 14:31:00  3278.0  3278.0  3278.0  3278.0    38.0
112  2018-03-06 14:33:00  3270.0  3270.0  3270.0  3270.0   100.0
113  2018-03-06 14:34:00  3270.0  3270.0  3270.0  3270.0     0.0
114  2018-03-06 14:40:00  3270.0  3270.0  3270.0  3270.0     0.0
115  2018-03-06 14:49:00  3270.0  3271.0  3270.0  3271.0   300.0
116  2018-03-06 14:57:00  3270.0  3270.0  3270.0  3270.0    20.0
117  2018-03-06 15:00:00  3270.0  3270.0  3270.0  3270.0     0.0
118  2018-03-09 13:42:00  3298.0  3298.0  3298.0  3298.0     4.0
119  2018-03-09 15:00:00  3298.0  3298.0  3298.0  3298.0     0.0

[120 rows x 6 columns]